### ISSUE TITLE
Retificação do exercício 1.13

### ISSUE THREAD

**Issue by Matheus-B-R** [valdigleis/Manuscrito#1]
Objetivo: Esta "issue" propõe mudanças de ordem textual e apresenta uma ligeira correção relativa aos bancos de dados.

Na página 35 do manuscrito, especificamente no exercício 1.13, lê-se: "Considere o banco de dados representado na Tabela 1.3. Esboce o conjunto gerado por cada Query detalhada abaixo e relacione essas Queries com as operações sobre conjuntos."

Sugere-se, para fins de promoção da concisão, coerência e coesão: "Considere o banco de dados representado na Tabela 1.3. para esboçar o conjunto gerado por cada "Query" detalhada abaixo, relacionando as mesmas com as operações sobre conjuntos."

Por fim, observa-se na tabela que tanto Rafaela quanto Júlio compartilham o mesmo id, recomendando-se a alteração de algum.

Atenciosamente,

Matheus Barros Rosa

**Comment by valdigleis** [comment]
Mudança textual aceita e implementada, apenas com o adendo de que o termo Query por se tratar de um termo em inglês deve ser redigindo em italico (com se encontra no manuscrito) segundo as normas da ABNT.

Quanto ao erro relacionado ao ID o mesmo também foi corrigido.
