### ISSUE TITLE
Sugestão de frase motivacional - Parte I

### ISSUE THREAD

**Issue by Matheus-B-R** [valdigleis/Manuscrito#3]
Esta issue propõe a incorporação de uma frase motivacional no capítulo 6.

"Não é o conhecimento, mas o ato de aprender, não a posse, mas o ato de chegar lá, que concede a maior satisfação.“, Carl Friedrich Gauss.

Com prazer,
Matheus Barros Rosa

**Comment by valdigleis** [comment]
No Capítulo 6 estou a decidir entre uma frase de Hilbert, Gödel ou de Turing já que o capítulo em questão trata de lógica.
