### ISSUE TITLE
Sugestão de frase motivacional - Parte II

### ISSUE THREAD

**Issue by Matheus-B-R** [valdigleis/Manuscrito#4]
Uma vez que ainda não foi definida uma frase motivacional para o capítulo 8, sugere-se:

"Não é o suficiente estar no lugar certo na hora certa. Você também precisa ter uma mente aberta no tempo certo.“, Paul Erdös.

Atenciosamente,
Matheus Barros Rosa

**Comment by valdigleis** [comment]
No capítulo 8 penso em colocar alguma de Herbrand ou do grande lógico brasileiro Newton da Costa!
